# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Fogel
email: legofneb+com@gmail.com
emailLabel: legofneb@gmail.com
description: Â© 2016 by Ben Fogel
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://legofneb.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  legofneb
github:
  repo: legofneb/legofneb.github.io
  branch: master

# Build settings
markdown: kramdown
